#!/bin/bash

if [ -z "$PYFILE" ]; then
    echo "Error: Environment variable PYFILE is not set."
    exit 1
fi

if [ ! -f "$PYFILE" ]; then
    echo "Error: File specified in PYFILE does not exist."
    exit 1
fi

python "$PYFILE"
